# Example ConfigMap and Secret for use with TerminalConfig

apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: default
data:
  app.properties: |
    # Application Configuration
    database.url=jdbc:postgresql://localhost/myapp
    database.driver=org.postgresql.Driver
    log.level=INFO
  nginx.conf: |
    server {
        listen 80;
        server_name localhost;
        location / {
            proxy_pass http://backend:8080;
        }
    }

---

apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: default
type: Opaque
data:
  # Base64 encoded values
  database.password: cGFzc3dvcmQxMjM=  # password123
  api.key: YWJjZGVmZ2hpams=  # abcdefghijk